# Generated by Django 4.0.6 on 2022-07-17 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('director', models.CharField(max_length=256)),
                ('stars', models.CharField(max_length=256)),
                ('genre', models.CharField(choices=[('drama', 'drama'), ('action', 'action'), ('adventure', 'adventure'), ('fantasy', 'fantasy'), ('thriller', 'thriller'), ('horror', 'horror'), ('comedy', 'comedy')], max_length=20)),
            ],
        ),
    ]
