# Generated by Django 4.0.6 on 2022-08-24 14:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mySite', '0002_movie_like_movie_unlike'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movieL', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_liked', to='mySite.movie')),
                ('userL', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_liked', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DisLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movieDL', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_disliked', to='mySite.movie')),
                ('userDL', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_disliked', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
